version: '2'
services:
    web:
        build: .
        ports:
            - "8081:5000"
        volumes:
            - .:/app
        environment:
            FLASK_APP: manage.py
            FLASK_ENV: production
